'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{EventEmitter}=require('node:events');
const {EmbeddedPlayer,embeddedArguments}=require('../embedded-player');
const request={url:'https://example.com/video.mp4',title:'A title',headers:{}};
function harness(){
 const children=[],sockets=[],events=[];
 const player=new EmbeddedPlayer({resourcesPath:'C:/engine',onEvent:e=>events.push(e),spawnProcess:()=>{const c=new EventEmitter();c.kill=()=>{c.killed=true;};children.push(c);return c;},connect:()=>{const s=new EventEmitter();s.writable=true;s.write=()=>{};s.destroy=()=>{s.destroyed=true;};sockets.push(s);return s;}});
 return {player,children,sockets,events};
}
test('embedding only accepts a main-process Windows handle',()=>{assert.throws(()=>embeddedArguments(request,{windowId:'123',pipe:'test',resourcesPath:'C:/engine'}));const args=embeddedArguments(request,{windowId:123,pipe:'test',resourcesPath:'C:/engine',start:Infinity});assert.ok(args.includes('--wid=123'));assert.ok(args.includes('--start=0'));assert.equal(args.at(-1),request.url);});
test('switching sources terminates old playback and ignores old events',async()=>{const h=harness();const first=h.player.start(request,123,{sessionId:'one'});h.sockets[0].emit('connect');await first;const second=h.player.start(request,123,{sessionId:'two'});assert.equal(h.children[0].killed,true);h.sockets[0].emit('data',Buffer.from('{"event":"property-change","name":"time-pos","data":15}\n'));assert.equal(h.events.filter(e=>e.type==='progress').length,0);h.sockets[1].emit('connect');await second;h.sockets[1].emit('data',Buffer.from('{"event":"property-change","name":"duration","data":100}\n{"event":"property-change","name":"time-pos","data":20}\n'));assert.deepEqual(h.events.at(-1),{type:'progress',position:20,duration:100,sessionId:'two'});h.player.stop();});
test('engine startup error is handled and returns to browsing',async()=>{const h=harness();const promise=h.player.start(request,123,{sessionId:'one'});h.children[0].emit('error',new Error('missing'));assert.equal((await promise).ok,false);assert.equal(h.player.session,null);assert.equal(h.events.at(-1).type,'closed');});
test('source errors after startup stop playback instead of leaving a black window',async()=>{const h=harness();const promise=h.player.start(request,123,{sessionId:'one'});h.sockets[0].emit('connect');await promise;h.sockets[0].emit('data',Buffer.from('{"event":"end-file","reason":"error"}\n'));assert.equal(h.player.session,null);assert.equal(h.children[0].killed,true);assert.equal(h.events[0].type,'error');});
